<a rel="nofollow" href="https://drjalily.com" target="_blank"><img style="max-width: 100%;" src="https://drjalily.com/web/images/banner/728.90-white.jpg" border="0" title="دکتر سعید جلیلی" alt="پایگاه اطلاع‌رسانی دکتر سعید جلیلی" /></a>

<!-- OghatSharee by www.1abzar.com ---><script type="text/javascript" src="https://1abzar.ir/abzar/tools/azan/v2/?mod=mod3&shahr=4-3"></script><div style="display:none"><h2><a href="https://www.1abzar.com/abzar/azan2.php">اوقات شرعی</a></h2></div><!-- OghatSharee by www.1abzar.com --->

<!-- Date Converter by www.1abzar.com ---><script type="text/javascript" src="https://1abzar.ir/abzar/tools/convert-date/?color=333333&bg=F4EFE8&kc=EDAB55&kadr=1"></script><div style="display:none"><h3><a href="https://www.1abzar.com/abzar/convert-date.php">&#1578;&#1576;&#1583;&#1740;&#1604; &#1578;&#1575;&#1585;&#1740;&#1582;</a></h3></div><!-- Date Converter by www.1abzar.com --->

<!-- Statistics by www.1abzar.com --->
<script type="text/javascript" src="https://1abzar.ir/abzar/tools/stat/amar-v3.php?color=333333&bg=F7F4D9&kc=888888&kadr=1&amar=wxzyqra3sbxy8-io9uvqbb7362gyrg&show=1|1|1|1|1|1|1"></script><div style="display:none"><h3><a href="https://www.1abzar.com/abzar/stat.php">&#1570;&#1605;&#1575;&#1585;&#1711;&#1740;&#1585; &#1608;&#1576;&#1604;&#1575;&#1711;</a></h3></div>
<!-- Statistics by www.1abzar.com --->


<a href="https://time.is/Tehran" id="time_is_link" rel="nofollow">زمان در تهران:</a>
<span id="Tehran_z442"></span>
<script src="//widget.time.is/fa.js"></script>
<script>
time_is_widget.init({Tehran_z442:{template:"TIME<br>DATE<br>SUN", date_format:"dayname, monthname dnum, year, week", sun_format:"طلوع آفتاب: srhour:srminute غروب آفتاب: sshour:ssminute<br>طول روز: dlhoursساعت dlminutesدقیقه", coords:"35.6943900,51.4215100"}});
</script>
